### ISSUE TITLE
The constructor NdefMessage(NdefRecord) is undefined 

### ISSUE THREAD

**Issue by skzinzuwadia** [skjolber/Fagmote#1]
I got issue with HelloWorldNFCActivity in 

@Override
    public NdefMessage createNdefMessage(NfcEvent event) {
        Log.d(TAG, "createNdefMessage");

```
    // create record to be pushed
    TextRecord record = new TextRecord("This is my text record");

    // encode one or more record to NdefMessage
    return new NdefMessage(record.getNdefRecord());
}
```

The constructor NdefMessage(NdefRecord) is undefined in line  "return new NdefMessage(record.getNdefRecord());"

**Comment by skjolber** [comment]
I guess that constructor is just for the later versions of Android. Oh well. :+1:
